// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  label: string;
  labelWrap: string;
  pokemonAbilities: string;
  pokemonCard: string;
  pokemonImage: string;
  pokemonName: string;
  pokemonPic: string;
  pokemonStats: string;
  root: string;
}
export const cssExports: CssExports;
export default cssExports;
