// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'pokemonCards': string;
  'pokemonInput': string;
  'pokemonSpinner': string;
  'root': string;
  'spin': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
